remote_theme: "mmistakes/minimal-mistakes@4.26.2"
title: "Filgaia"
title_separator: "|"
subtitle: "Alone in the fields"
name: "A. F. Perez"
url: "https://filgaia.github.io"
baseurl: "/blog"
repository: "filgaia/blog"
plugins: ["jekyll-include-cache"]
include: ["_pages"]
minimal_mistakes_skin: "dark"
search: true

author:
  name: "A. F. Perez"
  location: "Somewhere, Colombia"
  avatar: "/assets/images/avatar.jpg"
  bio: "self-taught writer, passionate about fantasy stories, Nordic mythology, Japanese animation and visual novels"
  links:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/filgaiaco/"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/alejandroasp/"
    - label: "Xbox"
      icon: "fab fa-fw fa-xbox"
      url: "https://www.trueachievements.com/gamer/Yorha+agent"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/filgaia"
    - label: "Youtube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/@filgaiaco"
    - label: "Mercadolibre"
      icon: "fab fa-fw fa-shopify"
      url: "https://filgaia.mercadoshops.com.co"
    

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      toc: true
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: true
      read_time: true
      share: true
      related: true
